name: astrocyte
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-image
  - h5py
  - openpyxl
  - pytables
  - tqdm
  - pillow
  - tifffile
  - opencv
  - lightgbm
  - kneed
  - upsetplot
  - pytorch
  - cpuonly
  - pip:
      - matplotlib-venn
      - pycatch22
      - sktime
      - scikit-multilearn
      - rastermap
